Fedora 31
PowerShell/PowerShell-Docker pull request #494
Opened 2020-10-08 00:14 UTC by RDIL

Fixes #449

2020-10-12 23:12 UTC, TravisEz13 commented on release/stable/fedora31/docker/Dockerfile
> +FROM ${imageRepo}:${fromTag} AS installer-env
```suggestion
FROM ${imageRepo}:31 AS installer-env
```

2020-10-12 23:13 UTC, TravisEz13 commented on release/stable/fedora31/getLatestTag.ps1
> +$repoRoot = Join-Path -path (Join-Path -Path $parent -ChildPath '..') -ChildPath '..'
delete this file

2020-10-12 23:15 UTC, TravisEz13 requested changes

2020-10-12 23:15 UTC, TravisEz13 commented on release/stable/fedora31/meta.json
> +        "fedora31-#shorttag#"
```suggestion
        "#psversion#-fedora-31-#fulltag#",
        "#psversion#-fedora-#shorttag#",
        "fedora-31-#shorttag#"
```

2020-10-16 15:55 UTC, anamnavi commented
Given that you have removed the getLatestTag.ps1 script and we have removed fromTag from other Linux images (alpine, amazonlinux, kalilinux from this [issue](https://github.com/PowerShell/PowerShell-Docker/pull/503)) I think we could remove the fromTag from this Fedora image. (Unless there is a reason for keeping it that I'm not aware of). However, I see we have other Fedora31, Fedora30) so I could change them and Fedora32 to not use fromTag in a different PR

2020-10-16 16:19 UTC, RDIL commented
I'll take care of it for fedora @anamnavi

2020-10-19 16:50 UTC, TravisEz13 commented on release/stable/fedora32/meta.json
> +        "#psversion#-fedora-32-#shorttag#",
```suggestion
        "#psversion#-fedora-32",
```

2020-10-19 16:50 UTC, TravisEz13 commented on release/stable/fedora32/docker/Dockerfile
> +FROM ${imageRepo}:${fromTag} AS installer-env
```suggestion
FROM ${imageRepo}:32 AS installer-env
```

2020-10-19 16:50 UTC, TravisEz13 commented on release/stable/fedora32/docker/Dockerfile
> +ARG fromTag=32
```suggestion
```

2020-10-19 16:51 UTC, TravisEz13 commented on release/stable/fedora32/docker/Dockerfile
> +ARG fromTag=32
```suggestion
```

2020-10-19 16:51 UTC, TravisEz13 commented on release/stable/fedora32/docker/Dockerfile
> +    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-Fedora-${fromTag}
```suggestion
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-Fedora-32
```

2020-10-19 16:51 UTC, TravisEz13 requested changes
see comments

2020-10-19 19:03 UTC, TravisEz13 approved these changes

2020-10-19 19:03 UTC, merged