Distribution requests
PowerShell/PowerShell-Docker pull request #538
Opened 2021-02-08 16:10 UTC by anamnavi

## PR Summary

Distribution support was requested [here ](https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ADistribution-Request+label%3AArea-DSC)for Centos 7.3-7.9, RedHat 7.4-7.8, and SLES 12, 15.

So far I have added support for the Centos versions.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/docs/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

2021-02-08 16:29 UTC, RDIL approved these changes
LGTM

2021-02-09 19:06 UTC, TravisEz13 requested changes

2021-02-09 19:06 UTC, TravisEz13 commented on release/preview/rhel7.6/docker/Dockerfile
> +FROM registry.access.redhat.com/ubi7/ubi:7.6 AS installer-env
speak offline

2021-02-12 19:45 UTC, TravisEz13 commented on release/preview/centos7.9/meta.json
> +        {"Tag": "7.9.2009"}
short tag should be 7.9
```suggestion
        {"Tag": "7.9"}
```

2021-02-12 19:46 UTC, TravisEz13 commented on release/preview/centos7.8/meta.json
> +        {"Tag": "7.8.2003"}
```suggestion
        {"Tag": "7.8"}
```

2021-02-12 19:46 UTC, TravisEz13 commented on release/preview/centos7.7/meta.json
> +        {"Tag": "7.7.1908"}
```suggestion
        {"Tag": "7.7"}
```

2021-02-12 19:46 UTC, TravisEz13 commented on release/preview/centos7.6/meta.json
> +        {"Tag": "7.6.1810"}
```suggestion
        {"Tag": "7.6"}
```

2021-02-12 19:47 UTC, TravisEz13 requested changes

2021-02-12 19:47 UTC, TravisEz13 commented on release/preview/centos7.5/meta.json
> +        {"Tag": "7.5.1804"}
```suggestion
        {"Tag": "7.5"}
```

2021-02-12 19:47 UTC, TravisEz13 commented on release/preview/centos7.4/meta.json
> +        {"Tag": "7.4.1708"}
```suggestion
        {"Tag": "7.4"}
```

2021-02-12 19:47 UTC, TravisEz13 commented on release/preview/centos7.3/meta.json
> +        {"Tag": "7.3.1611"}
```suggestion
        {"Tag": "7.3"}
```

2021-02-12 19:48 UTC, TravisEz13 commented
![image](https://user-images.githubusercontent.com/10873629/107815361-257cfe00-6d28-11eb-8ced-08c314e6e7e1.png)

Move these to unstable

2021-02-13 03:58 UTC, RDIL commented
For arch: https://github.com/FZUG/repo/issues/16

2021-02-16 20:43 UTC, anamnavi commented
@RDIL do you mean that just for archlinux or blackarch too?

> For arch: [FZUG/repo#16](https://github.com/FZUG/repo/issues/16)

2021-02-16 21:57 UTC, TravisEz13 requested changes

2021-02-16 21:57 UTC, TravisEz13 commented on release/preview/centos7.3/docker/Dockerfile
> +FROM centos:7.3.1611 as installer-env
we should let it float in the from tag as well, otherwise you need to setup dependabot on each image, your choice.

2021-02-24 17:36 UTC, TravisEz13 commented
CI is failing.

2021-02-24 17:37 UTC, TravisEz13 commented
Actually, I think we can discard the centos part of this PR and just keep the moves to unstable?

2021-02-25 20:12 UTC, atlslscsrv-app approved these changes

2021-02-25 21:47 UTC, TravisEz13 approved these changes

2021-02-25 21:47 UTC, merged